# Create a file list in the correct order
echo "file '上.mp3'" > list.txt
echo "file '天.mp3'" >> list.txt
echo "file '玄.mp3'" >> list.txt
echo "file '靈.mp3'" >> list.txt
echo "file '愛.mp3'" >> list.txt
echo "file '自.mp3'" >> list.txt
echo "file '生.mp3'" >> list.txt
echo "file '靈.mp3'" >> list.txt
echo "file '七.mp3'" >> list.txt
echo "file '思.mp3'" >> list.txt
echo "file '七.mp3'" >> list.txt
echo "file '召.mp3'" >> list.txt
echo "file '三.mp3'" >> list.txt
echo "file '現.mp3'" >> list.txt
echo "file '隨.mp3'" >> list.txt
echo "file '迎.mp3'" >> list.txt
echo "file '代.mp3'" >> list.txt
echo "file '予.mp3'" >> list.txt
echo "file '之.mp3'" >> list.txt
echo "file '形.mp3'" >> list.txt
echo "file '形.mp3'" >> list.txt
echo "file '隨.mp3'" >> list.txt
echo "file '物.mp3'" >> list.txt
echo "file '化.mp3'" >> list.txt
echo "file '應.mp3'" >> list.txt
echo "file '化.mp3'" >> list.txt
echo "file '而.mp3'" >> list.txt
echo "file '成.mp3'" >> list.txt
echo "file '熟.mp3'" >> list.txt
echo "file '急.mp3'" >> list.txt
echo "file '如.mp3'" >> list.txt
echo "file '律.mp3'" >> list.txt
echo "file '令.mp3'" >> list.txt